import 'package:flutter/material.dart';

/// Catalogue of Material icons available to choose for a category.
///
/// Keys are snake_case strings that match the Material icon names (so the
/// stored `iconCode` is self-describing and stable across migrations). Look
/// up with [iconForCode]; iterate with [iconSections] for the picker UI.
///
/// Currently ~170 icons grouped into purpose-built sections. To add more,
/// drop the icon under the appropriate section list — the picker rebuilds
/// from this list automatically.

const Map<String, List<String>> iconSections = {
  'Food & Drink': [
    'restaurant',
    'restaurant_menu',
    'local_cafe',
    'local_bar',
    'lunch_dining',
    'breakfast_dining',
    'dinner_dining',
    'brunch_dining',
    'fastfood',
    'ramen_dining',
    'local_pizza',
    'cake',
    'bakery_dining',
    'icecream',
    'set_meal',
    'takeout_dining',
    'room_service',
    'wine_bar',
    'sports_bar',
    'liquor',
    'coffee',
    'emoji_food_beverage',
  ],
  'Groceries & Shopping': [
    'shopping_cart',
    'shopping_basket',
    'shopping_bag',
    'store',
    'storefront',
    'local_grocery_store',
    'local_mall',
    'local_convenience_store',
    'sell',
    'local_offer',
    'redeem',
    'card_giftcard',
  ],
  'Transport': [
    'directions_car',
    'directions_bus',
    'directions_subway',
    'directions_train',
    'directions_bike',
    'directions_walk',
    'directions_boat',
    'train',
    'tram',
    'two_wheeler',
    'motorcycle',
    'local_taxi',
    'local_shipping',
    'flight',
    'sailing',
    'electric_scooter',
    'electric_bike',
    'electric_car',
    'car_rental',
    'car_repair',
    'local_parking',
    'local_gas_station',
    'ev_station',
    'commute',
    'pedal_bike',
  ],
  'Home & Utilities': [
    'home',
    'house',
    'cottage',
    'apartment',
    'bed',
    'chair',
    'weekend',
    'kitchen',
    'bathtub',
    'shower',
    'dry_cleaning',
    'local_laundry_service',
    'iron',
    'lightbulb',
    'thermostat',
    'hvac',
    'plumbing',
    'handyman',
    'build',
    'construction',
    'yard',
    'grass',
    'deck',
    'fireplace',
    'water_drop',
    'electrical_services',
    'gas_meter',
    'wifi',
    'router',
    'tv',
  ],
  'Health & Wellness': [
    'medical_services',
    'local_hospital',
    'local_pharmacy',
    'vaccines',
    'masks',
    'fitness_center',
    'self_improvement',
    'monitor_heart',
    'healing',
    'medication',
    'health_and_safety',
    'sports_gymnastics',
    'spa',
    'psychology',
    'mood',
    'sentiment_satisfied',
  ],
  'Entertainment': [
    'movie',
    'theaters',
    'sports_esports',
    'casino',
    'music_note',
    'library_music',
    'queue_music',
    'sports_basketball',
    'sports_soccer',
    'sports_football',
    'sports_baseball',
    'sports_tennis',
    'sports_golf',
    'sports_volleyball',
    'sports_hockey',
    'gamepad',
    'attractions',
    'festival',
    'celebration',
    'party_mode',
    'nightlife',
    'theater_comedy',
    'mic',
    'event',
  ],
  'Bills & Money': [
    'receipt',
    'receipt_long',
    'account_balance',
    'account_balance_wallet',
    'attach_money',
    'credit_card',
    'payment',
    'payments',
    'monetization_on',
    'savings',
    'paid',
    'request_quote',
    'currency_exchange',
    'currency_bitcoin',
    'price_change',
    'price_check',
  ],
  'Education': [
    'school',
    'menu_book',
    'library_books',
    'auto_stories',
    'book',
    'edit_note',
    'science',
    'calculate',
    'biotech',
    'class_',
  ],
  'Pets': [
    'pets',
    'cruelty_free',
  ],
  'Work & Business': [
    'work',
    'business_center',
    'business',
    'computer',
    'laptop',
    'phone_iphone',
    'smartphone',
    'print',
    'badge',
    'mail',
    'cases',
  ],
  'Travel': [
    'flight_takeoff',
    'hotel',
    'luggage',
    'beach_access',
    'public',
    'map',
    'explore',
    'place',
    'hiking',
    'pool',
  ],
  'Personal & Beauty': [
    'face',
    'content_cut',
    'person',
    'child_care',
    'accessibility',
    'palette',
    'brush',
    'visibility',
    'cleaning_services',
  ],
  'Misc': [
    'star',
    'favorite',
    'label',
    'category',
    'gift',
    'volunteer_activism',
    'eco',
    'recycling',
    'language',
    'security',
    'lock',
    'key',
    'shield',
    'verified',
    'help',
    'info',
    'warning',
    'priority_high',
    'extension',
    'widgets',
  ],
};

/// Flat lookup: code → IconData. Built lazily from [iconSections].
const Map<String, IconData> _iconCatalog = {
  // Food & Drink
  'restaurant': Icons.restaurant,
  'restaurant_menu': Icons.restaurant_menu,
  'local_cafe': Icons.local_cafe,
  'local_bar': Icons.local_bar,
  'lunch_dining': Icons.lunch_dining,
  'breakfast_dining': Icons.breakfast_dining,
  'dinner_dining': Icons.dinner_dining,
  'brunch_dining': Icons.brunch_dining,
  'fastfood': Icons.fastfood,
  'ramen_dining': Icons.ramen_dining,
  'local_pizza': Icons.local_pizza,
  'cake': Icons.cake,
  'bakery_dining': Icons.bakery_dining,
  'icecream': Icons.icecream,
  'set_meal': Icons.set_meal,
  'takeout_dining': Icons.takeout_dining,
  'room_service': Icons.room_service,
  'wine_bar': Icons.wine_bar,
  'sports_bar': Icons.sports_bar,
  'liquor': Icons.liquor,
  'coffee': Icons.coffee,
  'emoji_food_beverage': Icons.emoji_food_beverage,

  // Groceries & Shopping
  'shopping_cart': Icons.shopping_cart,
  'shopping_basket': Icons.shopping_basket,
  'shopping_bag': Icons.shopping_bag,
  'store': Icons.store,
  'storefront': Icons.storefront,
  'local_grocery_store': Icons.local_grocery_store,
  'local_mall': Icons.local_mall,
  'local_convenience_store': Icons.local_convenience_store,
  'sell': Icons.sell,
  'local_offer': Icons.local_offer,
  'redeem': Icons.redeem,
  'card_giftcard': Icons.card_giftcard,

  // Transport
  'directions_car': Icons.directions_car,
  'directions_bus': Icons.directions_bus,
  'directions_subway': Icons.directions_subway,
  'directions_train': Icons.directions_train,
  'directions_bike': Icons.directions_bike,
  'directions_walk': Icons.directions_walk,
  'directions_boat': Icons.directions_boat,
  'train': Icons.train,
  'tram': Icons.tram,
  'two_wheeler': Icons.two_wheeler,
  'motorcycle': Icons.motorcycle,
  'local_taxi': Icons.local_taxi,
  'local_shipping': Icons.local_shipping,
  'flight': Icons.flight,
  'sailing': Icons.sailing,
  'electric_scooter': Icons.electric_scooter,
  'electric_bike': Icons.electric_bike,
  'electric_car': Icons.electric_car,
  'car_rental': Icons.car_rental,
  'car_repair': Icons.car_repair,
  'local_parking': Icons.local_parking,
  'local_gas_station': Icons.local_gas_station,
  'ev_station': Icons.ev_station,
  'commute': Icons.commute,
  'pedal_bike': Icons.pedal_bike,

  // Home & Utilities
  'home': Icons.home,
  'house': Icons.house,
  'cottage': Icons.cottage,
  'apartment': Icons.apartment,
  'bed': Icons.bed,
  'chair': Icons.chair,
  'weekend': Icons.weekend,
  'kitchen': Icons.kitchen,
  'bathtub': Icons.bathtub,
  'shower': Icons.shower,
  'dry_cleaning': Icons.dry_cleaning,
  'local_laundry_service': Icons.local_laundry_service,
  'iron': Icons.iron,
  'lightbulb': Icons.lightbulb,
  'thermostat': Icons.thermostat,
  'hvac': Icons.hvac,
  'plumbing': Icons.plumbing,
  'handyman': Icons.handyman,
  'build': Icons.build,
  'construction': Icons.construction,
  'yard': Icons.yard,
  'grass': Icons.grass,
  'deck': Icons.deck,
  'fireplace': Icons.fireplace,
  'water_drop': Icons.water_drop,
  'electrical_services': Icons.electrical_services,
  'gas_meter': Icons.gas_meter,
  'wifi': Icons.wifi,
  'router': Icons.router,
  'tv': Icons.tv,

  // Health & Wellness
  'medical_services': Icons.medical_services,
  'local_hospital': Icons.local_hospital,
  'local_pharmacy': Icons.local_pharmacy,
  'vaccines': Icons.vaccines,
  'masks': Icons.masks,
  'fitness_center': Icons.fitness_center,
  'self_improvement': Icons.self_improvement,
  'monitor_heart': Icons.monitor_heart,
  'healing': Icons.healing,
  'medication': Icons.medication,
  'health_and_safety': Icons.health_and_safety,
  'sports_gymnastics': Icons.sports_gymnastics,
  'spa': Icons.spa,
  'psychology': Icons.psychology,
  'mood': Icons.mood,
  'sentiment_satisfied': Icons.sentiment_satisfied,

  // Entertainment
  'movie': Icons.movie,
  'theaters': Icons.theaters,
  'sports_esports': Icons.sports_esports,
  'casino': Icons.casino,
  'music_note': Icons.music_note,
  'library_music': Icons.library_music,
  'queue_music': Icons.queue_music,
  'sports_basketball': Icons.sports_basketball,
  'sports_soccer': Icons.sports_soccer,
  'sports_football': Icons.sports_football,
  'sports_baseball': Icons.sports_baseball,
  'sports_tennis': Icons.sports_tennis,
  'sports_golf': Icons.sports_golf,
  'sports_volleyball': Icons.sports_volleyball,
  'sports_hockey': Icons.sports_hockey,
  'gamepad': Icons.gamepad,
  'attractions': Icons.attractions,
  'festival': Icons.festival,
  'celebration': Icons.celebration,
  'party_mode': Icons.party_mode,
  'nightlife': Icons.nightlife,
  'theater_comedy': Icons.theater_comedy,
  'mic': Icons.mic,
  'event': Icons.event,

  // Bills & Money
  'receipt': Icons.receipt,
  'receipt_long': Icons.receipt_long,
  'account_balance': Icons.account_balance,
  'account_balance_wallet': Icons.account_balance_wallet,
  'attach_money': Icons.attach_money,
  'credit_card': Icons.credit_card,
  'payment': Icons.payment,
  'payments': Icons.payments,
  'monetization_on': Icons.monetization_on,
  'savings': Icons.savings,
  'paid': Icons.paid,
  'request_quote': Icons.request_quote,
  'currency_exchange': Icons.currency_exchange,
  'currency_bitcoin': Icons.currency_bitcoin,
  'price_change': Icons.price_change,
  'price_check': Icons.price_check,

  // Education
  'school': Icons.school,
  'menu_book': Icons.menu_book,
  'library_books': Icons.library_books,
  'auto_stories': Icons.auto_stories,
  'book': Icons.book,
  'edit_note': Icons.edit_note,
  'science': Icons.science,
  'calculate': Icons.calculate,
  'biotech': Icons.biotech,
  // `class` is a reserved Dart keyword — use `class_` as the catalog key
  // while still mapping to `Icons.class_`.
  'class_': Icons.class_,

  // Pets
  'pets': Icons.pets,
  'cruelty_free': Icons.cruelty_free,

  // Work & Business
  'work': Icons.work,
  'business_center': Icons.business_center,
  'business': Icons.business,
  'computer': Icons.computer,
  'laptop': Icons.laptop,
  'phone_iphone': Icons.phone_iphone,
  'smartphone': Icons.smartphone,
  'print': Icons.print,
  'badge': Icons.badge,
  'mail': Icons.mail,
  'cases': Icons.cases,

  // Travel
  'flight_takeoff': Icons.flight_takeoff,
  'hotel': Icons.hotel,
  'luggage': Icons.luggage,
  'beach_access': Icons.beach_access,
  'public': Icons.public,
  'map': Icons.map,
  'explore': Icons.explore,
  'place': Icons.place,
  'hiking': Icons.hiking,
  'pool': Icons.pool,

  // Personal & Beauty
  'face': Icons.face,
  'content_cut': Icons.content_cut,
  'person': Icons.person,
  'child_care': Icons.child_care,
  'accessibility': Icons.accessibility,
  'palette': Icons.palette,
  'brush': Icons.brush,
  'visibility': Icons.visibility,
  'cleaning_services': Icons.cleaning_services,

  // Misc
  'star': Icons.star,
  'favorite': Icons.favorite,
  'label': Icons.label,
  'category': Icons.category,
  'gift': Icons.card_giftcard, // alias
  'volunteer_activism': Icons.volunteer_activism,
  'eco': Icons.eco,
  'recycling': Icons.recycling,
  'language': Icons.language,
  'security': Icons.security,
  'lock': Icons.lock,
  'key': Icons.key,
  'shield': Icons.shield,
  'verified': Icons.verified,
  'help': Icons.help,
  'info': Icons.info,
  'warning': Icons.warning,
  'priority_high': Icons.priority_high,
  'extension': Icons.extension,
  'widgets': Icons.widgets,
};

/// Looks up the icon for a stored `iconCode`. Returns a neutral fallback
/// (`Icons.label`) when the code isn't known so old data never crashes the
/// UI after a code rename.
IconData iconForCode(String code) {
  return _iconCatalog[code] ?? Icons.label;
}

/// Returns every available code in display order (sections preserved).
List<String> get allIconCodes => [
  for (final entry in iconSections.entries) ...entry.value,
];

/// Curated palette for the colour picker — covers warm/cool/neutral.
const List<Color> categoryColorPalette = [
  Color(0xFFEF4444), // red
  Color(0xFFF59E0B), // amber
  Color(0xFFEAB308), // yellow
  Color(0xFF22C55E), // green
  Color(0xFF10B981), // emerald
  Color(0xFF14B8A6), // teal
  Color(0xFF06B6D4), // cyan
  Color(0xFF0EA5E9), // sky
  Color(0xFF3B82F6), // blue
  Color(0xFF6366F1), // indigo
  Color(0xFF8B5CF6), // violet
  Color(0xFFA855F7), // purple
  Color(0xFFD946EF), // fuchsia
  Color(0xFFEC4899), // pink
  Color(0xFFF43F5E), // rose
  Color(0xFF78716C), // stone
  Color(0xFF6B7280), // grey
  Color(0xFF1F2937), // slate
  Color(0xFF92400E), // brown
  Color(0xFF166534), // forest
];
